language: elixir
elixir:
  - 1.2.3
  - 1.7.4
  - 1.9.2
before_script:
  - mix local.hex --force
  - mix deps.get
script:
  - mix test
after_script:
  - mix deps.get
  - mix inch.report
cache:
  directories:
    - deps
