language: elixir
elixir:
  - 1.7.4

jobs:
  include:
    - elixir: '1.10.4'
      otp_release: '21.0'
    - elixir: '1.9.4'
      otp_release: '21.0'

script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - MIX_ENV=test mix test --cover

cache:
  directories:
    - deps
